### ISSUE TITLE
how can using local openai style api with reppl

### ISSUE THREAD

**Issue by datalee** [appl-team/reppl#1]
Reimplementing Complex Prompt Optimization Algorithm within Two Hours

replace gpt to local openai api？

**Comment by dhh1995** [comment]
Thanks for your questions.

Please follow this [setup guide](https://appl-team.github.io/appl/setup/#override-configs) to override the servers and the `default_servers`:

For example, you can include an `appl.yaml` in the root directory of your project:
```yaml
default_servers:
  default: my_local_default  # you can change the name as long as it can be found in `servers`
  small: my_local_small  # if you want to configure for the small model, or `null` to make sure it falls back to the default model
  large: my_local_large  # if you want to configure for the small model, or `null` to make sure it falls back to the default model

servers:
  my_local_default:
    model: custom/default
    base_url: "http://localhost:30000/v1" # replace with the actual URL for the model
  # [optional] If you want to set the small model (which is served in another port, let's say 30001)
  my_local_small:
    model: custom/default
    base_url: "http://localhost:30001/v1"
```

Note that the local model needs to be compatible with OpenAI's API interface.

**Comment by datalee** [comment]
> Thanks for your questions.
> 
> Please follow this [setup guide](https://appl-team.github.io/appl/setup/#override-configs) to override the servers and the `default_servers`:
> 
> For example, you can include an `appl.yaml` in the root directory of your project:
> 
> ```yaml
> default_servers:
>   default: my_local_default  # you can change the name as long as it can be found in `servers`
>   small: my_local_small  # if you want to configure for the small model, or `null` to make sure it falls back to the default model
>   large: my_local_large  # if you want to configure for the small model, or `null` to make sure it falls back to the default model
> 
> servers:
>   my_local_default:
>     model: custom/default
>     base_url: "http://localhost:30000/v1" # replace with the actual URL for the model
>   # [optional] If you want to set the small model (which is served in another port, let's say 30001)
>   my_local_small:
>     model: custom/default
>     base_url: "http://localhost:30001/v1"
> ```
> 
> Note that the local model needs to be compatible with OpenAI's API interface.

thks

**Comment by datalee** [comment]
> Thanks for your questions.
> 
> Please follow this [setup guide](https://appl-team.github.io/appl/setup/#override-configs) to override the servers and the `default_servers`:
> 
> For example, you can include an `appl.yaml` in the root directory of your project:
> 
> ```yaml
> default_servers:
>   default: my_local_default  # you can change the name as long as it can be found in `servers`
>   small: my_local_small  # if you want to configure for the small model, or `null` to make sure it falls back to the default model
>   large: my_local_large  # if you want to configure for the small model, or `null` to make sure it falls back to the default model
> 
> servers:
>   my_local_default:
>     model: custom/default
>     base_url: "http://localhost:30000/v1" # replace with the actual URL for the model
>   # [optional] If you want to set the small model (which is served in another port, let's say 30001)
>   my_local_small:
>     model: custom/default
>     base_url: "http://localhost:30001/v1"
> ```
> 
> Note that the local model needs to be compatible with OpenAI's API interface.

with vllm local servers just like this?
> [!NOTE]
> 
servers:
  qwen:
    model: qwen2.5-72b-chat
    base_url: "http://xx:8001/v1"  

setting:
`gen("qwen")`

but get errors:
`ValueError: Unable to map your input to a model. Check your input - {'messages': [{'content': 'Hello World! My name is APPL.', 'role': 'user'}], 'timeout': None, 'temperature': None, 'top_p': None, 'n': None, 'stream': None, 'stream_options': None, 'stop': None, 'max_completion_tokens': None, 'max_tokens': None, 'modalities': None, 'prediction': None, 'audio': None, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': None, 'user': None, 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'logprobs': None, 'top_logprobs': None, 'parallel_tool_calls': None, 'deployment_id': None, 'extra_headers': None, 'functions': None, 'function_call': None, 'base_url': 'http://xxx:8001/v1', 'api_version': None, 'api_key': 'NotRequired', 'model_list': None, 'kwargs': {'custom_llm_provider': '-72b-chat', 'litellm_call_id': '95283bce-e544-49fc-acba-00dac2859531', 'litellm_logging_obj': <litellm.litellm_core_utils.litellm_logging.Logging object at 0x0000023671840A60>}, 'model': 'qwen2.5-72b-chat'}
`

**Comment by dhh1995** [comment]
APPL does not start any local models but relies on local-hosted APIs.

You can start your vllm server for Qwen like:
```bash
vllm serve Qwen/Qwen2.5-7B-Instruct # replace this with the model you want.
```

let's assume the URL is "http://localhost:8000", then you can config APPL like this:

```yaml
default_servers:
  default: qwen

servers:
  qwen:
    model: custom/default
    base_url: "http://localhost:8000/v1"
```

Note that only the base_url is being used in APPL, not the qwen model. You can adjust the model on the `vllm serve` command if you want, or configure different models into different ports.

Then you can call: `gen("qwen")` to use this server, or just `gen()` if you configure the `defaul_servers` as "qwen" in the example above.

**Comment by datalee** [comment]
> APPL does not start any local models but relies on local-hosted APIs.
> 
> You can start your vllm server for Qwen like:
> 
> ```shell
> vllm serve Qwen/Qwen2.5-7B-Instruct # replace this with the model you want.
> ```
> 
> let's assume the URL is "http://localhost:8000", then you can config APPL like this:
> 
> ```yaml
> default_servers:
>   default: qwen
> 
> servers:
>   qwen:
>     model: custom/default
>     base_url: "http://localhost:8000/v1"
> ```
> 
> Note that only the base_url is being used in APPL, not the qwen model. You can adjust the model on the `vllm serve` command if you want, or configure different models into different ports.请注意，APPL 中仅使用了 base_url，而不是 qwen 模型。如果需要，您可以在 vllmserve 命令上调整模型，或者将不同的模型配置到不同的端口。
> 
> Then you can call: `gen("qwen")` to use this server, or just `gen()` if you configure the `defaul_servers` as "qwen" in the example above.

vllm openai style api，must give `"model": "xxx",`，otherwise get error：`{
	"object": "error",
	"message": "[{'type': 'missing', 'loc': ('body', 'model'), 'msg': 'Field required', 'input': {'temperature': 0.45, 'top_p': 0.8, 'max_tokens': 1024, 'stream': False, 'messages': [{'role': 'system', 'content': '你是一个智能助手，你为用户生成综合质量（包括有用性，事实性，无害性）极好的回复。'}, {'role': 'user', 'content': \"xxxxx'''\"}]}}]",
	"type": "BadRequestError",
	"param": null,
	"code": 400
}`

**Comment by dhh1995** [comment]
Could you be more specific about the error?
what's your vllm version, what command do you use for serving vllm models? which command encountered the error you pasted here?
For more details about serving models using vllm, please see this [page](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html).

Thanks!

**Comment by datalee** [comment]
#> Could you be more specific about the error? what's your vllm version, what command do you use for serving vllm models? which command encountered the error you pasted here? For more details about serving models using vllm, please see this [page](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html).
> 
> Thanks!

vllm 0.4.2，serving command：`python -m vllm.entrypoints.openai.api_server --model="$MODEL_NAME" --tensor-parallel-size=$TP --gpu-memory-utilization=0.95 --max-model-len=$MAX_MODEL_LEN --trust-remote-code --host=0.0.0.0 --port=$PORT --dtype=$DTYPE --served-model-name=$SERVED_MODEL_NAME `

the command encountered error is：
```python
from appl import gen, ppl

@ppl  # the @ppl decorator marks the function as an `APPL function`
def greeting(name: str):
    f"Hello World! My name is {name}."  # Add text to the prompt
    return gen("qwen")  # call the default LLM with the current prompt

print(greeting("APPL"))  # call `greeting` as a normal Python function
```

**Comment by dhh1995** [comment]
Not sure if you are serving models using vllm correctly.

Could you try the example [here](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#openai-compatible-server)? could you serve the model and run the model through the OpenAI python package as in the example?

If you can run the example correctly, you may need to update the model name in the `appl.yaml` config file as:
```yaml
servers:
  qwen:
    model: custom/... # custom/<the model name>, for example: custom/NousResearch/Meta-Llama-3-8B-Instruct
    base_url: "http://localhost:8000/v1"
```
